version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python version 3.11 ..."
      - pyenv global $PYTHON_311_VERSION
      - apt-get update
      - apt-get install -y awscli
 
  pre_build:
    commands:
      - echo "Executing pre_build phase..."
 
  build:
    commands:
      - aws s3 cp s3://jenkins-backup16/testkey.pem /opt/testkey.pem
      - chmod 400 /opt/testkey.pem
      - scp -o StrictHostKeyChecking=no -i /opt/testkey.pem ubuntu@54.226.78.10:/opt/output.csv /tmp/jenkins_details.csv
      
      - aws s3 cp /tmp/jenkins_details.csv s3://jenkins-backup16/
      
 
  post_build:
    commands:
      - echo "Executing post_build phase..."
